### ISSUE TITLE
Custom Template Screen

### ISSUE THREAD

**Issue by Zighome24** [scorecast/scorecast#7]
# Custom Template Screen
### A screen that will allow the user to create a customized game template for their type of game.

This is going to be hard. I'm thinking for this screen that we should offer a series of properties and ranges of values for these properties that the user can provide for the game.

Example Properties:
- Point Value Increment Option [0-infinity]: -- **(multiple of these could be added to the properties)**
- Number of Teams [1 or 2-10]: -- **(10 teams not necessarily a limit; teams should be positive)**
- Team Starting Score [0-infinity]: -- **(multiple of these possible; number of these should be limited to number of teams added above)**
- Winning Game Score [1-infinity]: --
- Win By 2? [true/false]: --
- Automatic Win if difference greater than [1-infinity]: --
- Automatic Win if difference less than [1-infinity]: --
These are just examples, there would probably have to be a lot more options. For the start we are going to program our own custom templates and in doing that figure out what other properties we might want.

**Comment by jackbonaguro** [comment]
Consider closing; as we discussed is is unreasonable for the MVP in-app since it's too complex and not useful to 99% of target audience.

A web interface and template documentation is necessary though.
